services:
  auth-db:
    image: mongo
    container_name: auth-db
    restart: always
    volumes:
      - auth-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - auth-network

  auth-service:
    depends_on:
      - auth-db
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3001:3000"
    volumes:
      - ./auth-service:/app
    networks:
      - auth-network

volumes:
  auth-data:

networks:
  auth-network:
    driver: bridge