services:
  auth-db:
    image: mongo
    container_name: auth-db
    ports:
      - "27018:27017"
    volumes:
      - auth-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    #networks:
    #  - auth-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3001:3000"
    depends_on:
      - auth-db
    volumes:
      - ./auth-service:/app
    #networks:
    #  - auth-network

volumes:
  auth-data:

# networks:
#   auth-network:
#     driver: bridge
