services:
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - auth-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - auth-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3001:${PORT}"
    depends_on:
      - auth-db
    volumes:
      - ./auth-service:/app
    networks:
      - auth-network

volumes:
  auth-data:

networks:
  auth-network:
    driver: bridge
