services:
  auth-db:
    image: mongo
    container_name: auth-db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - auth-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3001:3000"
    volumes:
      - ./auth-service:/app

volumes:
  auth-data: